name: Build Pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.21
      - name: Build
        run: deno task build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build